# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eec3c7429b6ed1394139a8d446f8c482e66e39efe21b1d2ccf2f7dec63a224ab10567fd7ddd93e037f5b5534ca31e4b78f6ccd8e65bbc6aededb9ea455ead565

test:
  secret_key_base: 744a7726232dbe28862252a329709a7e03c24784d63801950ba3dcf0f0d31925ccb15274caa7ecba335f5997383e064e47d6ebedaeab86bbf659a62463df8b23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
